
spring:
  cloud:
    config:
      uri: http://localhost:7001
eureka:
  server:
    #剔除异常挂掉的实例调度频率默认60秒下为5秒（测试环境）
    eviction-interval-timer-in-ms: 5000
    #应用下线后有缓存  缓存过期应用下线 或者调整缓存过期时间
    use-read-only-response-cache: false
    #response-cache-auto-expiration-in-seconds: 60
    #测试环境关闭自我保护机制
    enable-self-preservation: false
    peer-eureka-nodes-update-interval-ms: 10000 #默认是10分钟即600000，这里为了验证改为10秒
  client:
    #是否将该实例注册到eureka-server
    registerWithEureka: false
    #是否检索服务
    fetchRegistry: false
    #客户端拉取服务端注册信息的频率
    registry-fetch-interval-seconds: 5
management: #actuator 开启监控跟踪
  endpoints:
    web:
      exposure:
        include: '*'
